name: deploy to gh-pages
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Install and Build
        run: |
          npm install
          git remote set-url origin ${{ secrets.GH_PAGE_TOKEN }}@github.com:siakhooi/reactjs-tutorial-tic-tac-toe.git
          npm run deploy
